[package]
edition = '2021'
name = 'ever_bls_lib'
version = '0.1.45'

[dependencies]
criterion = '0.3'
failure = '0.1.6'
rand = '0.7'
rand_chacha = '0.2'
blst = { features = [ 'portable' ], version = '0.3.5' }

